os: linux
language: generic
dist: focal

jobs:
  include:
    - stage: "Tests"
      name: "Create custom image 1"
      vm:
        create:
          name: 04-org-images-t1
      script:
        - echo "Running Job 1"
    - stage: "Tests"
      name: "Create custom image 2"
      vm:
        create:
          name: 04-org-images-t2
      script:
        - echo "Running Job 2"
    - stage: "Tests"
      name: "Create custom image 3"
      vm:
        create:
          name: 04-org-images-t3
      script:
        - echo "Running Job 3"
    - stage: "Tests"
      name: "Create custom image 4"
      vm:
        create:
          name: 04-org-images-t4
      script:
        - echo "Running Job 4"
    - stage: "Tests"
      name: "Create custom image 5"
      vm:
        create:
          name: 04-org-images-t5
      script:
        - echo "Running Job 5"
